### ISSUE TITLE
readlightnovel.org

### ISSUE THREAD

**Issue by AdrianSimionov** [dipu-bd/site-to-epub#1]
Please add support for readlightnovel.org

**Comment by dipu-bd** [comment]
Hopefully by the middle of this month I can add it. *Too busy with life right now* :frowning_face:

**Comment by AdrianSimionov** [comment]
Looking forward to it.

**Comment by dipu-bd** [comment]
It is done.

Example:
- URL: https://www.readlightnovel.org/tales-of-herding-gods the
- Novel Id: `tales-of-herding-gods`
- Run `python . readln tales-of-herding-gods 1 100`
