### ISSUE TITLE
Novel binding fails

### ISSUE THREAD

**Issue by backsy** [dipu-bd/site-to-epub#11]
> Processing: _novel\8093990805004205\
> !! Failed to bind: _novel\8093990805004205

This is with when providing the chapter numbers.

> python3 __main__.py webnovel 8093990805004205
> Getting CSRF Token from  https://www.webnovel.com/book/8093990805004205
> CSRF Token = BEwNDFH7yoADt2uvgWH9Y2ZdxMHKanalcugCh9WI
> Getting book name and chapter list...
> 1646 chapters found
> Processing: _novel\8093990805004205\
> Creating: NA\NA_v.epub
> 
> *************************************************************
>  Amazon kindlegen(Windows) V2.9 build 1029-0897292
>  A command line e-book compiler
>  Copyright Amazon.com and its Affiliates 2014
> *************************************************************
> 
> Info:I9007:option: -c2: Kindle Huffdic compression
> Error(opfparser):E20004: the id in the spine does not match any item in the manifest: cover

That is without giving chapter numbers.

**Comment by dipu-bd** [comment]
I am working on it.

You can use the package from pip in the mean time: 

```
python3 -m pip install --user ebook-crawler 
```

**Comment by dipu-bd** [comment]
check now, it should be fixed in the latest commits

**Comment by backsy** [comment]
Yep works.
