### ISSUE TITLE
output_path referenced before assignment

### ISSUE THREAD

**Issue by backsy** [dipu-bd/site-to-epub#12]
Installed using pip on windows. Created the folders manually. See #10 .

> .\ebook_crawler.exe webnovel 8093990805004205
> Getting CSRF Token from  https://www.webnovel.com/book/8093990805004205
> CSRF Token = LI1UErwQVWiDGnvCmmpgBamfOpavmDGUCZJqglkP
> Getting book name and chapter list...
> 1646 chapters found
> Traceback (most recent call last):
>   File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Karl\AppData\Roaming\Python\Python36\Scripts\ebook_crawler.exe\__main__.py", line 9, in <module>
>   File "C:\Users\Karl\AppData\Roaming\Python\Python36\site-packages\ebook_crawler\__init__.py", line 34, in main
>     end_chapter=sys.argv[4] if len(sys.argv) > 4 else ''
>   File "C:\Users\Karl\AppData\Roaming\Python\Python36\site-packages\ebook_crawler\webnovel.py", line 44, in start
>     novel_to_kindle(self.output_path)
>   File "C:\Users\Karl\AppData\Roaming\Python\Python36\site-packages\ebook_crawler\binding.py", line 83, in novel_to_kindle
>     for file_name in sorted(os.listdir(output_path)):
> UnboundLocalError: local variable 'output_path' referenced before assignment

**Comment by backsy** [comment]
Works if i use manual chapter range.

**Comment by dipu-bd** [comment]
i have fixed it. by the way, you should at least provide the starting chapter to download

**Comment by backsy** [comment]
Meaning the beginning chapter isnt truly optional as stated in the readme.
