### ISSUE TITLE
Output chapters as plain text (.txt)

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/site-to-epub#13]

**Comment by yudilee** [comment]
I think in helper file, in save chapter file we can use beautiful soup to get text file from chapter title and body text and save it to text file in folder text, do you think we need to implement it?

**Comment by dipu-bd** [comment]
yes, I am working on it. i finally got some free time to work on this project again

**Comment by yudilee** [comment]
> yes, I am working on it. i finally got some free time to work on this project again

Great. Thank you

**Comment by dipu-bd** [comment]
It is done in v2.1.0
