### ISSUE TITLE
MAc user

### ISSUE THREAD

**Issue by kalvinMB** [dipu-bd/site-to-epub#16]
Hi, A beginner here,
Can you please provide us an instruction for mac users? thank you

**Comment by yudilee** [comment]
I guess the tutorial on main page is still aplicable, so firts you install python3 and make sure you can run py file. Next, install "site to epub" using pip as told in tutorial and test to run ebook_crawler in terminal.

**Comment by kalvinMB** [comment]
Thanks alot Yudilee,
However, I am pretty noob with this app actually. (layman here)

can you please list down what to do? Like using PIP ? what does it mean? 
sorry for the hassle. 

thanks

**Comment by yudilee** [comment]
> I think i get the hang of it.
> 
> So can you please instruct me for an example what code should i type in if i want to download a-will-eternal from chapters 1 to 3 from wuxiaworld.co?
> 
> i have error : No module named 'requests'

in terminal just type
ebook_crawler wuxiac A-Will-Eternal 1 3
or 
ebook_crawler wuxiac A-Will-Eternal http://www.wuxiaworld.co/A-Will-Eternal/1042888.html http://www.wuxiaworld.co/A-Will-Eternal/1042890.html

for error no module named request, if you have already installed pip3 or pip you can just install module using
pip3 install requests

**Comment by kalvinMB** [comment]
> > I think i get the hang of it.
> > So can you please instruct me for an example what code should i type in if i want to download a-will-eternal from chapters 1 to 3 from wuxiaworld.co?
> > i have error : No module named 'requests'
> 
> in terminal just type
> ebook_crawler wuxiac A-Will-Eternal 1 3
> or
> ebook_crawler wuxiac A-Will-Eternal http://www.wuxiaworld.co/A-Will-Eternal/1042888.html http://www.wuxiaworld.co/A-Will-Eternal/1042890.html
> 
> for error no module named request, if you have already installed pip3 or pip you can just install module using
> pip3 install requests

Thank you so much.. yudilee. In behalf of all the mac users, you are Peerless. 💯

**Comment by yudilee** [comment]
> > > I think i get the hang of it.
> > > So can you please instruct me for an example what code should i type in if i want to download a-will-eternal from chapters 1 to 3 from wuxiaworld.co?
> > > i have error : No module named 'requests'
> > 
> > 
> > in terminal just type
> > ebook_crawler wuxiac A-Will-Eternal 1 3
> > or
> > ebook_crawler wuxiac A-Will-Eternal http://www.wuxiaworld.co/A-Will-Eternal/1042888.html http://www.wuxiaworld.co/A-Will-Eternal/1042890.html
> > for error no module named request, if you have already installed pip3 or pip you can just install module using
> > pip3 install requests
> 
> Thank you so much.. yudilee. In behalf of all the mac users, you are Peerless. 100

Thanks for trying this amazing e book creator from @dipu-bd. I found this amazing script and want other people also enjoy it. First off all Thanks a lot to @dipu-bd and thanks to you to try it out. Let's share it so other people can also enjoy it.
