### ISSUE TITLE
WuxiaWorld new URL format

### ISSUE THREAD

**Issue by PragmaticConfusion** [dipu-bd/site-to-epub#2]
The new format for WW novels is 
http://www.wuxiaworld.com/novel/desolate-era/de-book-x-chapter-x/
, with the old format being
http://www.wuxiaworld.com/desolate-era-index/de-book-x-chapter-x/.

Can you edit the wuxia code to change that?

**Comment by dipu-bd** [comment]
Entire design of wuxiaworld has been changed :disappointed:

**Comment by dipu-bd** [comment]
I modified the code to add support for the new format. Did not have enough time to test thoroughly. Report issue if you find anything wrong.
