### ISSUE TITLE
I already create 2 crawler for Indonesian source site for mtl novel. May i add it in this project source crawler?

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/site-to-epub#20]
Hi, Sudipto

Recently i need to add 2 source to this great project. Both of the source is Indonesia language machine translation novel provider. They are lnindo and idqidian, both have quite a lot of collection. Some of my friend ask me to create epub from that site. I have already create i and test it. May i add it in pull request?

Best Regard

Yudi Lee

**Comment by dipu-bd** [comment]
Yeah, sure! I have merged your previous pull request with `dev`. Make sure to pull and merge it first.

**Comment by yudilee** [comment]
> Yeah, sure! I have merged your previous pull request with `dev`. Make sure to pull and merge it first.

Thank you
