### ISSUE TITLE
Convert old crawlers to new style

### ISSUE THREAD

**Issue by dipu-bd** [dipu-bd/site-to-epub#22]
Convert all old style crawlers to [new simplified style](https://github.com/dipu-bd/site-to-epub/blob/master/ebook_crawler/_sample.py). And add them to [`ebook_crawler/__init__.py`](https://github.com/dipu-bd/site-to-epub/blob/master/ebook_crawler/__init__.py#L17).

- [x] https://lnmtl.com
- [x] https://www.webnovel.com
- [x] https://www.wuxiaworld.com
- [x] https://www.wuxiaworld.co
- [x] https://boxnovel.com
- [x] https://www.readlightnovel.org
- [x] https://novelplanet.com
- [x] https://lnindo.org
- [x] https://www.idqidian.us

**Comment by yudilee** [comment]
I create pull request for converting old crawler to new style. The new style is really good. Made me easier to add new source.

**Comment by yudilee** [comment]
With the last pull is this issue considered solved?

**Comment by dipu-bd** [comment]
yes. I needed some time to review it
