### ISSUE TITLE
Webnovel error invalid literal for int() with base 10:

### ISSUE THREAD

**Issue by yudilee** [dipu-bd/site-to-epub#7]
While i try to create epub from webnovel i got error invalid literal for int() with base 10:

python3  __main__.py webnovel 10377938706023605 https://www.webnovel.com/book/10377938706023605/27858104469219628/Last-Wish-System/Yale-Roanmad https://www.webnovel.com/book/10377938706023605/30154170363336851/Last-Wish-System/Crossing-the-Border
Getting CSRF Token from  https://www.webnovel.com/book/10377938706023605
CSRF Token = 9eJJFX5txT0r9s3004p1rDY61DZrTfvslGGHmp61
Getting book name and chapter list...
148 chapters found
Traceback (most recent call last):
  File "__main__.py", line 2, in <module>
    main()
  File "/home/yudi/book/Web Scrapper/ebook_crawler/__init__.py", line 34, in main
    end_chapter=sys.argv[4] if len(sys.argv) > 4 else ''
  File "/home/yudi/book/Web Scrapper/ebook_crawler/webnovel.py", line 43, in start
    self.get_chapter_bodies()
  File "/home/yudi/book/Web Scrapper/ebook_crawler/webnovel.py", line 83, in get_chapter_bodies
    start = int(self.start_chapter)
ValueError: invalid literal for int() with base 10: 'https://www.webnovel.com/book/10377938706023605/27858104469219628/Last-Wish-System/Yale-Roanmad'

Thanks for helping

**Comment by jdtcoder** [comment]
Hello @yudilee . Please use chapter numbers instead. 

**For example:**
`ebook_crawler webnovel 1 115`

**Comment by dipu-bd** [comment]
fixed in latest release
